services:
  - type: web
    name: plaschema
    env: php
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && npm ci && npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: PLASCHEMA
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: plaschema
          type: web
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: plaschema-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: plaschema-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: plaschema-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: plaschema-db
          property: password

databases:
  - name: plaschema-db
    databaseName: plaschema
    ipAllowList: []
