name: Deploy to Shared Hosting

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper change detection

      # Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, gd, xml, zip, dom, fileinfo, curl
          coverage: none

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "plas-app/package-lock.json"

      - name: Install Composer Dependencies
        working-directory: ./plas-app
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Install NPM Dependencies
        working-directory: ./plas-app
        run: npm ci

      - name: Build Frontend Assets
        working-directory: ./plas-app
        run: npm run build

      - name: Generate .env file
        working-directory: ./plas-app
        run: |
          cp .env.example .env
          sed -i 's/APP_ENV=.*/APP_ENV=production/' .env
          sed -i 's/APP_DEBUG=.*/APP_DEBUG=false/' .env
          sed -i 's/APP_URL=.*/APP_URL=https:\/\/plaschema.pl.gov.ng/' .env
          php artisan key:generate
          # Make sure the .env file is readable
          chmod 644 .env
          cat .env | grep APP_  # Display APP settings for verification

      # Pre-generate cache files locally
      - name: Pre-generate cache files
        working-directory: ./plas-app
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Create necessary directories that might be missing
      - name: Create necessary directories
        working-directory: ./plas-app
        run: |
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/logs
          chmod -R 775 storage bootstrap/cache

      # Prepare deployment structure
      - name: Prepare deployment structure
        run: |
          # Create a deployment directory
          mkdir -p deployment

          # Copy the Laravel application to the laravel directory
          mkdir -p deployment/laravel
          cp -r plas-app/* deployment/laravel/
          # Remove public directory from laravel folder since we'll deploy it separately
          rm -rf deployment/laravel/public

          # Create public_html directory
          mkdir -p deployment/public_html

          # Copy only the public directory contents to public_html
          cp -r plas-app/public/* deployment/public_html/

          # Update the index.php to point to the correct paths (absolute paths)
          sed -i "s|/../vendor/autoload.php|/home/plaschem/laravel/vendor/autoload.php|g" deployment/public_html/index.php
          sed -i "s|/../bootstrap/app.php|/home/plaschem/laravel/bootstrap/app.php|g" deployment/public_html/index.php
          sed -i "s|/../../laravel/vendor/autoload.php|/home/plaschem/laravel/vendor/autoload.php|g" deployment/public_html/index.php
          sed -i "s|/../../laravel/bootstrap/app.php|/home/plaschem/laravel/bootstrap/app.php|g" deployment/public_html/index.php

          # Update the .env file with correct storage paths
          echo "STORAGE_PATH=/home/plaschem/laravel/storage" >> deployment/laravel/.env
          echo "PUBLIC_PATH=/home/plaschem/public_html" >> deployment/laravel/.env

          # Fix log path in .env to ensure logs are written to the correct location
          echo "LOG_PATH=/home/plaschem/laravel/storage/logs" >> deployment/laravel/.env

          # Verify .env file exists and is readable
          if [ -f "deployment/laravel/.env" ]; then
            echo ".env file exists and will be deployed"
            chmod 644 deployment/laravel/.env
            # Display the first few lines of the .env file (excluding sensitive data)
            head -n 10 deployment/laravel/.env
          else
            echo "ERROR: .env file is missing in deployment/laravel/"
            # Create a backup .env file if it's missing
            echo "Creating backup .env file..."
            echo "APP_NAME=Plaschema" > deployment/laravel/.env
            echo "APP_ENV=production" >> deployment/laravel/.env
            echo "APP_KEY=base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >> deployment/laravel/.env
            echo "APP_DEBUG=false" >> deployment/laravel/.env
            echo "APP_URL=https://plaschema.pl.gov.ng" >> deployment/laravel/.env
            echo "" >> deployment/laravel/.env
            echo "LOG_CHANNEL=stack" >> deployment/laravel/.env
            echo "LOG_DEPRECATIONS_CHANNEL=null" >> deployment/laravel/.env
            echo "LOG_LEVEL=debug" >> deployment/laravel/.env
            echo "LOG_PATH=/home/plaschem/laravel/storage/logs" >> deployment/laravel/.env
            echo "" >> deployment/laravel/.env
            echo "DB_CONNECTION=mysql" >> deployment/laravel/.env
            echo "DB_HOST=127.0.0.1" >> deployment/laravel/.env
            echo "DB_PORT=3306" >> deployment/laravel/.env
            echo "DB_DATABASE=plaschem_db" >> deployment/laravel/.env
            echo "DB_USERNAME=plaschem_user" >> deployment/laravel/.env
            echo "DB_PASSWORD=" >> deployment/laravel/.env
            echo "" >> deployment/laravel/.env
            echo "BROADCAST_DRIVER=log" >> deployment/laravel/.env
            echo "CACHE_DRIVER=file" >> deployment/laravel/.env
            echo "FILESYSTEM_DISK=local" >> deployment/laravel/.env
            echo "QUEUE_CONNECTION=sync" >> deployment/laravel/.env
            echo "SESSION_DRIVER=file" >> deployment/laravel/.env
            echo "SESSION_LIFETIME=120" >> deployment/laravel/.env
            echo "STORAGE_PATH=/home/plaschem/laravel/storage" >> deployment/laravel/.env
            echo "PUBLIC_PATH=/home/plaschem/public_html" >> deployment/laravel/.env
            chmod 644 deployment/laravel/.env
            echo "Backup .env file created."
          fi

          # Display the structure for verification
          echo "Deployment structure prepared:"
          find deployment -type d | sort
          ls -la deployment/laravel/ | grep -E "\.env|artisan"

      # Copy initialization file to public_html
      - name: Copy laravel utilities file to public_html
        run: |
          cp plas-app/public/laravel_utilities.php deployment/public_html/
          chmod 644 deployment/public_html/laravel_utilities.php

      # Create a directory structure helper file
      - name: Prepare directory structure helper
        run: |
          mkdir -p deployment/structure_helper/laravel
          mkdir -p deployment/structure_helper/laravel/app
          mkdir -p deployment/structure_helper/laravel/bootstrap/cache
          mkdir -p deployment/structure_helper/laravel/config
          mkdir -p deployment/structure_helper/laravel/database
          mkdir -p deployment/structure_helper/laravel/resources
          mkdir -p deployment/structure_helper/laravel/routes
          mkdir -p deployment/structure_helper/laravel/storage/app/public
          mkdir -p deployment/structure_helper/laravel/storage/framework/cache
          mkdir -p deployment/structure_helper/laravel/storage/framework/sessions
          mkdir -p deployment/structure_helper/laravel/storage/framework/views
          mkdir -p deployment/structure_helper/laravel/storage/logs
          echo "This file helps create the Laravel directory structure on the server." > deployment/structure_helper/README.txt
          touch deployment/structure_helper/laravel/.gitkeep
          touch deployment/structure_helper/laravel/app/.gitkeep
          touch deployment/structure_helper/laravel/bootstrap/cache/.gitkeep
          touch deployment/structure_helper/laravel/storage/app/public/.gitkeep
          touch deployment/structure_helper/laravel/storage/framework/cache/.gitkeep
          touch deployment/structure_helper/laravel/storage/framework/sessions/.gitkeep
          touch deployment/structure_helper/laravel/storage/framework/views/.gitkeep
          touch deployment/structure_helper/laravel/storage/logs/.gitkeep

      # Create backup of current deployment (if exists)
      - name: Create backup of current deployment
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deployment/structure_helper/
          server-dir: ./backup-$(date +%Y%m%d%H%M%S)/
          dangerous-clean-slate: false
          state-name: .ftp-deploy-sync-state-backup.json
          log-level: verbose
          timeout: 600000
          dry-run: false

      # Create Laravel directory on server
      - name: Create Laravel directory on server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deployment/structure_helper/
          server-dir: ./
          dangerous-clean-slate: false
          state-name: .ftp-deploy-sync-state-create-dir.json
          log-level: verbose
          timeout: 600000

      # Create storage directories with proper permissions
      - name: Create storage directories with proper permissions
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://plaschema.pl.gov.ng/laravel_utilities.php?utility=fix_cache&create_dirs=1
          method: "GET"
          timeout: 60000
          preventFailureOnNoResponse: true
          ignoreStatusCodes: true

      # Deploy Laravel core files
      - name: Deploy Laravel core files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deployment/laravel/
          server-dir: ./laravel/
          dangerous-clean-slate: false # Changed to false to preserve existing files if any
          state-name: .ftp-deploy-sync-state-laravel.json
          log-level: verbose
          timeout: 600000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            **/.github/**

      # Deploy public files
      - name: Deploy public files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deployment/public_html/
          server-dir: ./public_html/
          dangerous-clean-slate: false # Changed to false to preserve existing files if any
          state-name: .ftp-deploy-sync-state-public.json
          log-level: verbose
          timeout: 600000

      # Set proper permissions on server
      - name: Set proper permissions on server
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://plaschema.pl.gov.ng/laravel_utilities.php?utility=fix_cache
          method: "GET"
          timeout: 60000
          preventFailureOnNoResponse: true
          ignoreStatusCodes: true

      # Run post-deployment script
      - name: Run post-deployment script
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://plaschema.pl.gov.ng/laravel_utilities.php?utility=cache&action=clear_cache
          method: "GET"
          timeout: 60000
          preventFailureOnNoResponse: true
          ignoreStatusCodes: true

      # Create storage link
      - name: Create storage link
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://plaschema.pl.gov.ng/laravel_utilities.php?utility=storage_link
          method: "GET"
          timeout: 60000
          preventFailureOnNoResponse: true
          ignoreStatusCodes: true

      # Send deployment notification
      - name: Send deployment notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "PLASCHEMA website deployment ${{ job.status }}"
          SLACK_TITLE: "Deployment Status"
          SLACK_USERNAME: GitHub Actions
          SLACK_FOOTER: "Powered by GitHub Actions"
          MSG_MINIMAL: false
        continue-on-error: true

      - name: Post-deployment notification
        run: |
          echo "Deployment completed!"
          echo "IMPORTANT: Visit https://plaschema.pl.gov.ng/laravel_utilities.php in your browser to complete the setup."
          echo "Laravel core files deployed to: laravel/ (in your home directory)"
          echo "Public files deployed to: public_html/ (in your home directory)"

      # Create deployment status file for rollback reference
      - name: Create deployment status file
        run: |
          echo "Deployment completed at $(date)" > deployment_status.txt
          echo "Commit: ${{ github.sha }}" >> deployment_status.txt
          echo "Branch: ${{ github.ref }}" >> deployment_status.txt
          echo "Triggered by: ${{ github.actor }}" >> deployment_status.txt
